internal static class SimpleDemoReport
{
    internal static object BuildRequest(int a4WidthPx, int a4HeightPx, int marginPx, string outputFilename)
    {
        var contentW = Math.Max(1, a4WidthPx - (marginPx * 2));
        var contentH = Math.Max(1, a4HeightPx - (marginPx * 2));

        const int innerPx = 20;
        const int gapPx = 20;
        var innerW = Math.Max(1, contentW - (innerPx * 2));
        var innerH = Math.Max(1, contentH - (innerPx * 2));

        return new
        {
            report = new
            {
                reportObjects = new object[]
                {
                    new
                    {
                        id = "title",
                        type = "text",
                        x = marginPx + innerPx,
                        y = marginPx + innerPx,
                        width = innerW,
                        height = 70,
                        properties = new
                        {
                            text = "Simple Example Report",
                            fontSize = 30,
                            fontFamily = "Arial",
                            color = "#111827",
                            bold = true,
                            backgroundColor = "#f3f4f6",
                            borderWidth = 1,
                            borderColor = "#d1d5db",
                            textAlign = "center"
                        }
                    },
                    new
                    {
                        id = "intro",
                        type = "text",
                        x = marginPx + innerPx,
                        y = marginPx + innerPx + 85,
                        width = innerW,
                        height = 80,
                        properties = new
                        {
                            text = "This demonstrates text styling: size, color, background, border and alignment.",
                            fontSize = 14,
                            fontFamily = "Arial",
                            color = "#374151",
                            backgroundColor = "#ffffff",
                            borderWidth = 1,
                            borderColor = "#e5e7eb",
                            textAlign = "left"
                        }
                    },
                    new
                    {
                        id = "left",
                        type = "text",
                        x = marginPx + innerPx,
                        y = marginPx + innerPx + 180,
                        width = Math.Max(1, (innerW - gapPx) / 2),
                        height = 60,
                        properties = new
                        {
                            text = "Left aligned\n(bold)",
                            fontSize = 18,
                            fontFamily = "Arial",
                            color = "#1f2937",
                            bold = true,
                            backgroundColor = "#ecfeff",
                            borderWidth = 1,
                            borderColor = "#06b6d4",
                            textAlign = "left"
                        }
                    },
                    new
                    {
                        id = "right",
                        type = "text",
                        x = marginPx + innerPx + Math.Max(1, (innerW - gapPx) / 2) + gapPx,
                        y = marginPx + innerPx + 180,
                        width = Math.Max(1, (innerW - gapPx) / 2),
                        height = 60,
                        properties = new
                        {
                            text = "Right aligned\n(italic)",
                            fontSize = 18,
                            fontFamily = "Arial",
                            color = "#1f2937",
                            italic = true,
                            backgroundColor = "#fff7ed",
                            borderWidth = 1,
                            borderColor = "#fb923c",
                            textAlign = "right"
                        }
                    },
                    new
                    {
                        id = "footer",
                        type = "text",
                        x = marginPx + innerPx,
                        y = Math.Max(marginPx + innerPx, marginPx + innerPx + innerH - 40),
                        width = innerW,
                        height = 40,
                        properties = new
                        {
                            text = "Generated by reportgenerator-client",
                            fontSize = 12,
                            fontFamily = "Arial",
                            color = "#6b7280",
                            textAlign = "center"
                        }
                    }
                },
                canvasSettings = CanvasSettingsBuilder.Build(a4WidthPx, a4HeightPx, marginPx),
                parameters = Array.Empty<object>()
            },
            data = new { },
            output = new { format = "pdf", filename = outputFilename }
        };
    }
}
