apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: reportai-ingress
  namespace: reportai
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  ingressClassName: traefik
  rules:
    - host: excel-grid.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: excel-grid
                port:
                  number: 80
    - host: reportmaker.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: reportmaker
                port:
                  number: 80
    - host: sqlrest.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sqlrest
                port:
                  number: 80
    - host: reportgenerator.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: reportgenerator
                port:
                  number: 80
